/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaticImportTestRouteImport } from './routes/static-import-test'
import { Route as IndexRouteImport } from './routes/index'

const StaticImportTestRoute = StaticImportTestRouteImport.update({
  id: '/static-import-test',
  path: '/static-import-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/static-import-test': typeof StaticImportTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/static-import-test': typeof StaticImportTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/static-import-test': typeof StaticImportTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/static-import-test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/static-import-test'
  id: '__root__' | '/' | '/static-import-test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StaticImportTestRoute: typeof StaticImportTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/static-import-test': {
      id: '/static-import-test'
      path: '/static-import-test'
      fullPath: '/static-import-test'
      preLoaderRoute: typeof StaticImportTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StaticImportTestRoute: StaticImportTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
